import type { Metadata } from "next";
import "./global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-full antialiased'>
      <body>
        <main className='min-h-screen bg-[#0F1115] flex items-center justify-center px-4'>
          {children}
        </main>
      </body>
    </html>
  );
}
