import type { Metadata } from "next";
import Themed from "@/components/Themed";

import "./light.css";
import "./light-hc.css";
import "./light-mc.css";
import "./dark.css";
import "./dark-hc.css";
import "./dark-mc.css";
import "./global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body>
        <Themed>{children}</Themed>
      </body>
    </html>
  );
}

export default RootLayout;
